def initIDCardUI(self, parent_widget):
    from PyQt5.QtWidgets import QScrollArea
    layout = QHBoxLayout(parent_widget)
    layout.setContentsMargins(10, 10, 10, 10)
    left_panel = QWidget()
    left_panel.setFixedWidth(320)
    left_layout = QVBoxLayout(left_panel)
    left_layout.setAlignment(Qt.AlignTop)
    title_lbl = QLabel('<b>បោះពុម្ពកាតសម្គាល់ខ្លួន / ID Card Printer</b>')
    title_lbl.setFont(QFont('Khmer OS Battambang', 12))
    left_layout.addWidget(title_lbl)
    gb_id = QGroupBox('១. បញ្ចូលរូបកាត / Load ID Card')
    gb_id_layout = QVBoxLayout()
    self.btn_load_front = QPushButton('បញ្ចូលរូបកាតមុខ / Load Front')
    self.btn_load_front.setStyleSheet('background-color: #0084c7; color: white; padding: 10px; border-radius: 5px;')
    self.btn_load_front.clicked.connect(self.load_id_front)
    self.lbl_info_front = QLabel('')
    self.lbl_info_front.setStyleSheet('color: gray; font-size: 11px;')
    self.btn_load_back = QPushButton('បញ្ចូលរូបកាតក្រោយ / Load Back')
    self.btn_load_back.setStyleSheet('background-color: #0084c7; color: white; padding: 10px; border-radius: 5px;')
    self.btn_load_back.clicked.connect(self.load_id_back)
    self.lbl_info_back = QLabel('')
    self.lbl_info_back.setStyleSheet('color: gray; font-size: 11px;')
    self.btn_swap_id = QPushButton('ឆ្លាស់ទីតាំងកាត / Swap Cards')
    self.btn_swap_id.setStyleSheet('background-color: #f59e0b; color: white; padding: 10px; border-radius: 5px;')
    self.btn_swap_id.clicked.connect(self.swap_id_cards)
    self.btn_clear_id = QPushButton('លុបរូបកាត / Clear ID Cards')
    self.btn_clear_id.setStyleSheet('background-color: #e74c3c; color: white; padding: 10px; border-radius: 5px;')
    self.btn_clear_id.clicked.connect(self.clear_id_cards)
    self.cb_id_filter = QComboBox()
    self.cb_id_filter.addItems(['រូបដើម / Original', 'ពណ៌វេទមន្ត / Magic Color', 'ពណ៌ប្រផេះ / Grayscale', 'ស-ខ្មៅ / B&W Scan'])
    self.cb_id_filter.currentIndexChanged.connect(self.apply_id_filters)
    self.chk_id_ai = QCheckBox('ប្រើប្រាស់ AI បង្កើនភាពច្បាស់ (AI Enhance)')
    self.chk_id_ai.setStyleSheet('color: #d946ef; font-weight: bold;')
    self.chk_id_ai.stateChanged.connect(self.apply_id_filters)
    self.chk_id_rounded = QCheckBox('✂️ កាត់ស៊ុមគែមកោងកាត (Rounded Corners)')
    self.chk_id_rounded.setChecked(True)
    self.chk_id_rounded.setStyleSheet('color: #0ea5e9; font-weight: bold;')
    self.chk_id_rounded.stateChanged.connect(self.update_id_preview)
    gb_id_layout.addWidget(self.btn_load_front)
    gb_id_layout.addWidget(self.lbl_info_front)
    gb_id_layout.addWidget(self.btn_load_back)
    gb_id_layout.addWidget(self.lbl_info_back)
    gb_id_layout.addWidget(self.btn_swap_id)
    gb_id_layout.addWidget(QLabel('ប្រភេទពណ៌ / Color Filter:'))
    gb_id_layout.addWidget(self.cb_id_filter)
    gb_id_layout.addWidget(self.chk_id_ai)
    gb_id_layout.addWidget(self.chk_id_rounded)
    gb_id_layout.addWidget(self.btn_clear_id)
    gb_id.setLayout(gb_id_layout)
    left_layout.addWidget(gb_id)
    gb_paper = QGroupBox('២. ទំហំក្រដាស / Paper Size')
    gb_paper_layout = QVBoxLayout()
    self.cb_id_paper = QComboBox()
    self.cb_id_paper.addItems(['A4 (210 x 297 mm)', 'A5 (148 x 210 mm)', 'ក្រដាសរូបថត (10x15 cm)'])
    self.cb_id_paper.currentIndexChanged.connect(self.update_id_preview)
    gb_paper_layout.addWidget(self.cb_id_paper)
    gb_paper.setLayout(gb_paper_layout)
    left_layout.addWidget(gb_paper)
    gb_size = QGroupBox('៣. ទំហំកាត / Card Size (mm)')
    gb_size_layout = QHBoxLayout()
    self.sb_id_w = QDoubleSpinBox()
    self.sb_id_w.setRange(10, 300)
    self.sb_id_w.setValue(85.6)
    self.sb_id_w.setSuffix(' mm')
    self.sb_id_h = QDoubleSpinBox()
    self.sb_id_h.setRange(10, 300)
    self.sb_id_h.setValue(54.0)
    self.sb_id_h.setSuffix(' mm')
    self.btn_id_ratio_lock = QPushButton('🔒')
    self.btn_id_ratio_lock.setCheckable(True)
    self.btn_id_ratio_lock.setChecked(True)
    self.btn_id_ratio_lock.setFixedWidth(30)
    self.btn_id_ratio_lock.setToolTip('ចាក់សោរទំហំ (Lock Aspect Ratio)')
    self.id_ratio = 85.6 / 54.0

    def toggle_ratio(checked):
        if checked:
            self.btn_id_ratio_lock.setText('🔒')
            if self.sb_id_h.value() > 0:
                self.id_ratio = self.sb_id_w.value() / self.sb_id_h.value()
        else:
            self.btn_id_ratio_lock.setText('🔓')

    def w_changed(val):
        if self.btn_id_ratio_lock.isChecked():
            self.sb_id_h.blockSignals(True)
            self.sb_id_h.setValue(val / self.id_ratio)
            self.sb_id_h.blockSignals(False)
        self.update_id_preview()

    def h_changed(val):
        if self.btn_id_ratio_lock.isChecked():
            self.sb_id_w.blockSignals(True)
            self.sb_id_w.setValue(val * self.id_ratio)
            self.sb_id_w.blockSignals(False)
        self.update_id_preview()
    self.btn_id_ratio_lock.toggled.connect(toggle_ratio)
    self.sb_id_w.valueChanged.connect(w_changed)
    self.sb_id_h.valueChanged.connect(h_changed)
    gb_size_layout.addWidget(QLabel('ទទឹង (W):'))
    gb_size_layout.addWidget(self.sb_id_w)
    gb_size_layout.addWidget(self.btn_id_ratio_lock)
    gb_size_layout.addWidget(QLabel('កម្ពស់ (H):'))
    gb_size_layout.addWidget(self.sb_id_h)
    gb_size.setLayout(gb_size_layout)
    left_layout.addWidget(gb_size)
    gb_qty = QGroupBox('៤. ចំនួនបោះពុម្ព / Print Quantity')
    gb_qty_layout = QVBoxLayout()
    self.sb_id_qty = QSpinBox()
    self.sb_id_qty.setRange(1, 50)
    self.sb_id_qty.setValue(1)
    self.sb_id_qty.valueChanged.connect(self.update_id_preview)
    gb_qty_layout.addWidget(self.sb_id_qty)
    gb_qty.setLayout(gb_qty_layout)
    left_layout.addWidget(gb_qty)
    gb_margin = QGroupBox('៥. តម្រឹមកាត / Alignment & Margin')
    gb_margin_layout = QGridLayout()
    btn_center_h = QPushButton('កណ្តាល (ផ្ដេក)')
    btn_center_h.clicked.connect(self.id_center_h)
    btn_center_v = QPushButton('កណ្តាល (បញ្ឈរ)')
    btn_center_v.clicked.connect(self.id_center_v)
    btn_align_left = QPushButton('គែមឆ្វេង (Left)')
    btn_align_left.clicked.connect(self.id_align_left)
    btn_align_right = QPushButton('គែមស្តាំ (Right)')
    btn_align_right.clicked.connect(self.id_align_right)
    btn_align_top = QPushButton('គែមលើ (Top)')
    btn_align_top.clicked.connect(self.id_align_top)
    btn_align_bottom = QPushButton('គែមក្រោម (Bottom)')
    btn_align_bottom.clicked.connect(self.id_align_bottom)
    gb_margin_layout.addWidget(btn_center_h, 0, 0)
    gb_margin_layout.addWidget(btn_center_v, 0, 1)
    gb_margin_layout.addWidget(btn_align_left, 1, 0)
    gb_margin_layout.addWidget(btn_align_right, 1, 1)
    gb_margin_layout.addWidget(btn_align_top, 2, 0)
    gb_margin_layout.addWidget(btn_align_bottom, 2, 1)
    self.sb_id_margin_top = QDoubleSpinBox()
    self.sb_id_margin_bottom = QDoubleSpinBox()
    self.sb_id_margin_left = QDoubleSpinBox()
    self.sb_id_margin_right = QDoubleSpinBox()
    for sb in [self.sb_id_margin_top, self.sb_id_margin_bottom, self.sb_id_margin_left, self.sb_id_margin_right]:
        sb.setRange(0, 500)
        sb.setValue(10)
        sb.valueChanged.connect(self.update_id_preview)
    gb_margin_layout.addWidget(QLabel('គែមលើ (Top):'), 3, 0)
    gb_margin_layout.addWidget(self.sb_id_margin_top, 3, 1)
    gb_margin_layout.addWidget(QLabel('គែមក្រោម (Bottom):'), 4, 0)
    gb_margin_layout.addWidget(self.sb_id_margin_bottom, 4, 1)
    gb_margin_layout.addWidget(QLabel('គែមឆ្វេង (Left):'), 5, 0)
    gb_margin_layout.addWidget(self.sb_id_margin_left, 5, 1)
    gb_margin_layout.addWidget(QLabel('គែមស្តាំ (Right):'), 6, 0)
    gb_margin_layout.addWidget(self.sb_id_margin_right, 6, 1)
    gb_margin.setLayout(gb_margin_layout)
    left_layout.addWidget(gb_margin)
    layout.addWidget(left_panel)
    self.id_preview = PreviewWidget()
    self.id_preview.is_manual = True
    self.id_preview.photo_positions = []
    self.id_preview.itemDoubleClicked.connect(self.on_id_preview_double_clicked)
    scroll_area = QScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setStyleSheet('QScrollArea { background-color: #dbe2e9; border: none; }')
    scroll_area.setWidget(self.id_preview)
    layout.addWidget(scroll_area, 1)
    right_panel = QWidget()
    right_panel.setFixedWidth(200)
    right_layout = QVBoxLayout(right_panel)
    right_layout.setAlignment(Qt.AlignTop)
    btn_print_pdf = QPushButton('រក្សាទុកជា PDF')
    btn_print_pdf.setStyleSheet('background-color: #2b52ff; color: white; padding: 12px; font-weight: bold; border-radius: 5px;')
    btn_print_pdf.clicked.connect(self.save_id_pdf)
    btn_print_foxit = QPushButton('បញ្ចូនទៅ Foxit PDF')
    btn_print_foxit.setStyleSheet('background-color: #5850ec; color: white; padding: 12px; font-weight: bold; border-radius: 5px;')
    btn_print_foxit.clicked.connect(self.print_id_foxit)
    right_layout.addWidget(btn_print_pdf)
    right_layout.addWidget(btn_print_foxit)
    layout.addWidget(right_panel)
    self.id_front_cv_img = None
    self.id_back_cv_img = None
    self.id_front_pixmap = None
    self.id_back_pixmap = None
    self.update_id_preview()